services:
  # Backend API Service
  - type: web
    name: reciperush-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BASE_URL
        value: ${{RENDER_EXTERNAL_URL}}
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAILJS_PUBLIC_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: LOG_LEVEL
        value: error
      - key: ENABLE_DEBUG
        value: false
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: ENABLE_TEST_ENDPOINTS
        value: false
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: reciperush-frontend
    env: static
    plan: starter
    buildCommand: echo "Frontend is static HTML/CSS/JS"
    startCommand: echo "Static site - no build needed"
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
